# Задание 1

In [93]:
import numpy as np

In [94]:
a = np.array([[1, 2], [3, 3], [1, 
            6], [8, 11], [10, 7]])
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [95]:
mean_a = a.mean(axis = 0)
mean_a

array([4.6, 5.8])

# Задание 2

In [96]:
a_centered = a - mean_a
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

# Задание 3

In [97]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1]) / (a.shape[0] - 1)
a_centered_sp

10.400000000000002

# Задание 4

In [98]:
a_cov = np.cov(a.T)
a_cov [0, 1]

10.4